INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', '.357 Magnum', '1', '1.0', '1.5');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', '.50 Cal', '5', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', '.50 Cal Artillery', '5', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', '105 MM Cannon', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', '12.5 MM', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', '120 MM Cannon', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', '120 MM Mortar', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', '120mm Cannon', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', '125 MM Cannon', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', '125mm Cannon', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', '14.5mm Cannons', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', '155 MM Howitzer', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', '20 MM MK', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', '20MM', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', '20mm Vulcan', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', '227mm MLRS Launcher', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', '23 MM Cannon', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', '23mm Cannon', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', '30 Cal Machinegun', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', '30 MM Cannon', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', '50 Cal', '5', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', '50 Cal Machinegun', '5', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', '50 Cal Tripod', '5', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', '88 Flak Cannon', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AGS-17 Grenade Launcher', '5', '0.2', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK103 GP-30 Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK103 GP-30 HE', '2', '0.4', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK103 GP-30 Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK103 Red Dot Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK103 Red Dot Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK108 GP-30 Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK108 GP-30 HE', '2', '0.4', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK108 GP-30 Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK108 Red Dot Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK108 Red Dot Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK47', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK47 - Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK47 - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK47 Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK47 GP-25 Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK47 GP-25 HE', '2', '0.4', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK47 GP-25 Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK47 Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK47/GP-25', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK47/GP-25 - Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK47/GP-25 - Grenade', '2', '0.4', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK47/GP-25 - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK47/GP-25 Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK47/GP-25 Grenade', '2', '0.4', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK47/GP-25 Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK74', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK74 - Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK74 - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK74 Reflex', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK74-Reflex-Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK74-Reflex-Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK74/GP-25', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK74/GP-25 - Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK74/GP-25 - Grenade', '2', '0.4', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK74/GP-25 - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AK74/GP-25 Grenade', '2', '0.4', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AT Missile', '5', '0.2', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'AT4', '4', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'ATM', '4', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Adrenalin Gun', '1', '1.0', '1.5');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Ancient Ship Cannon', '5', '0.2', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Anti Air Artillery', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Anti Tank Mine', '4', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Anti-Tank Mine', '4', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Avenger Turret', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Boat Gun', '5', '0.2', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Bombs', '5', '0.2', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'CAR15 - Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'CAR15 - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'CAR15 Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'CAR15 Rifle - Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'CAR15 Rifle - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'CAR15 Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'CAR15-Reflex-Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'CAR15-Reflex-Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Car15 Reflex', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Claymore', '4', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Combat Knife', '4', '1.2', '1.8');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Dual 30mm Cannons', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'E M Cannon', '5', '0.2', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'EE9 Turret', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'EM Cannon', '5', '0.2', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Emplaced M60', '4', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'FAMAS F1 Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'FAMAS F1 Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'FIM-92A Stinger', '4', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'FN MAG (GPMG)', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'FN P90 - Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'FN P90 - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'FN-FNC', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'FN-FNC - Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'FN-FNC - Burst', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'FN-FNC - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'FN-MAG', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'FN-P90 Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'FN-P90 Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Flak Cannon', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Flamethrower', '4', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Frag Grenade', '4', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'G3', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'G3 - Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'G3 - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'G3 Rifle - Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'G3 Rifle - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'G36', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'G36 - Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'G36 - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'G36 Rifle - Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'G36 Rifle - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'GPMG', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Glock 17', '1', '1.0', '1.5');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Glock 17 Silenced', '1', '1.0', '1.5');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Glock 18C', '1', '1.0', '1.5');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Glock 18C Auto', '1', '1.0', '1.5');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Glock 18C Semi', '1', '1.0', '1.5');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Grenade Launcher', '5', '0.2', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'HE Grenade', '4', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'HELLFIRE', '5', '0.2', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'HK 416 Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'HK 416 Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'HK G36E Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'HK G36E Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'HK G3A3 Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'HK G3A3 Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'HK MP5/10 Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'HK MP5/10 Burst', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'HK MP5/10 Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'HK MP5SD5 Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'HK MP5SD5 Burst', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'HK MP5SD5 Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'HKG36', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'HKG36 - Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'HKG36 - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'HYDRA 70mm', '5', '0.2', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Javelin', '4', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'KA-50 Gun', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'KA-52 Gun', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Knife', '4', '1.2', '1.8');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Kord Machinegun', '5', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'L115A', '3', '0.6', '0.9');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'L115A Sniper Rifle', '3', '0.6', '0.9');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'L1A1 Rifle - Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'L1A1 Rifle - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'L85A1 Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'L85A1 Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'L96A1', '3', '0.6', '0.9');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M 60', '2', '0.5', '0.7');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M-870 (00 Buckshot)', '1', '1.0', '1.5');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M-870(SSG Slug)', '1', '1.0', '1.5');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M-9', '1', '1.0', '1.5');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M107 .50 Cal', '3', '0.6', '0.9');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M107 Barret', '3', '0.6', '0.9');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M16', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M16 - Burst', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M16 - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M16 Rifle - Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M16 Rifle - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M16/M203', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M16/M203 - Burst', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M16/M203 - Grenade', '2', '0.4', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M16/M203 - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M16/M203 Grenade', '2', '0.4', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M16/M203 Rifle - Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M16/M203 Rifle - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M16A2 - Burst', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M16A2 - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M16A2/M203 - Burst', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M16A2/M203 - Grenade', '2', '0.4', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M16A2/M203 - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M16A3', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M16A3 - Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M16A3 - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M16A3 Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M16A3 Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M16A4', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M16A4 M203 Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M16A4 M203 HE', '2', '0.4', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M16A4 M203 Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M16A4/M203', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M16A4/M203 Grenade', '2', '0.4', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M18 Claymore', '4', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M1911A', '1', '1.0', '1.5');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M1911A1', '1', '1.0', '1.5');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M21', '3', '0.6', '0.9');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M21 Sniper Rifle', '3', '0.6', '0.9');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M224 - Frag', '4', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M224 - HE', '4', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M224 Mortar', '4', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M224 Mortar(HE)', '4', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M24', '3', '0.6', '0.9');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M24 Sniper Rifle', '3', '0.6', '0.9');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M240', '2', '0.5', '0.7');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M240 Machine Gun', '2', '0.5', '0.7');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M249', '2', '0.5', '0.7');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M249 Machine Gun', '2', '0.5', '0.7');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M249 SAW', '2', '0.5', '0.7');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M4', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M4 - Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M4 - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M4 Reflex', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M4 Rifle - Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M4 Rifle - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M4-Reflex-Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M4-Reflex-Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M4/M203', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M4/M203 - Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M4/M203 - Grenade', '2', '0.4', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M4/M203 - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M4/M203 Grenade', '2', '0.4', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M4/M203 Rifle - Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M4/M203 Rifle - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M4A1 Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M4A1 M203 Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M4A1 M203 HE', '2', '0.4', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M4A1 M203 Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M4A1 Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M60', '2', '0.5', '0.7');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M60 Machine Gun', '2', '0.5', '0.7');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M82', '3', '0.6', '0.9');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M82 .50 Cal', '3', '0.6', '0.9');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M82 Sniper Rifle', '3', '0.6', '0.9');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M870 Buckshot', '1', '1.0', '1.5');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M870 SSG Slug', '1', '1.0', '1.5');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M9', '1', '1.0', '1.5');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M9 Bayonet', '1', '1.0', '1.5');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M9 Beretta', '1', '1.0', '1.5');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'M9 Beretta Pistol', '1', '1.0', '1.5');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'MK-23', '1', '1.0', '1.5');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'MK-23 Pistol', '1', '1.0', '1.5');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'MP5 10mm', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'MP5 SMG', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'MP5 SMG Silenced', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'MP5 Silenced', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'MP5/10', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'MP5/10-Aim-Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'MP5/10-Aim-Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'MP5/SA2', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'MP5/SA2 Aimpoint', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'MP5/SD', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'MP5/SD2', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'MP5/SD2 Aimpoint', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'MP5SA2', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'MP5SD 9x19 Subsonic', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'MP5SD-Aim-Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'MP5SD-Aim-Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'MP5SD2', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Machete', '4', '1.2', '1.8');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Masterkey - Semi SG', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Masterkey Rifle - Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Masterkey Rifle - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Mex 50 Cal Machinegun', '5', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Minigun', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Molotov Cocktail', '4', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Mortar', '4', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'P-500 Basalt Launcher', '5', '0.2', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'P90', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'P90 - Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'P90 - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'P90 SMG - Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'P90 SMG - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'PKM', '2', '0.5', '0.7');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'PSG-1', '3', '0.6', '0.9');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'PSG-1 Rifle', '3', '0.6', '0.9');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'PSG-1 Silenced', '3', '0.6', '0.9');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'PSG-1 Sniper Rifle', '3', '0.6', '0.9');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'PSG-1SD', '3', '0.6', '0.9');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'RPG-7', '4', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'RPG7', '4', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'RPK-47', '2', '0.5', '0.7');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'RPK-47 SAW', '2', '0.5', '0.7');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'RPK-74', '2', '0.5', '0.7');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'RPK-74 Machine Gun', '2', '0.5', '0.7');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Rockets', '5', '0.2', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'S&W 357 Magnum', '1', '1.0', '1.5');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'SAM', '5', '0.2', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'SAM Launcher', '5', '0.2', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'SIG 552 - Auto', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'SIG 552 - Burst', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'SIG 552 - Semi', '2', '0.8', '1.2');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'SR-25', '3', '0.6', '0.9');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'SR-25 Rifle', '3', '0.6', '0.9');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'SR-25 Silenced', '3', '0.6', '0.9');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'SVD', '3', '0.6', '0.9');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'SVD Dragunov', '3', '0.6', '0.9');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'SVD Sniper Rifle', '3', '0.6', '0.9');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Satchel', '4', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Satchel Charge', '4', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Shotgun', '1', '1.0', '1.5');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Shotgun Pump-Action', '1', '1.0', '1.5');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Shotgun Semi-Auto', '1', '1.0', '1.5');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Shotgun pump', '1', '1.0', '1.5');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Sidewinders', '5', '0.2', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Slug Shotgun', '1', '1.0', '1.5');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Stinger', '4', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'TOW', '5', '0.2', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Tactical Nuke', '5', '0.2', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Thermite Grenade', '4', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Veh 120mm Cannon', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Veh 125mm Cannon', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Veh 155mm Howitzer', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Veh 20mm Cannon', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Veh 30mm Cannon', '5', '0.2', '0.3');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Veh AT Missle', '5', '0.2', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Veh SAM Launcher', '5', '0.2', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'Walther 2000 Silenced', '3', '0.6', '0.9');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'ZSU-23 50 Cal', '5', '0.3', '0.1');
INSERT INTO `{rating_table}` (`s_type`, `s_name`, `s_stat`, `s_pts`, `s_pts2`) VALUES ('wpnBonus', 'ZU-23 Gun', '5', '0.2', '0.3');