<?php
/*/////////////////////////////////////////////////////////////
//                                                           //
// JOStats is a product of Bab.stats                         //
//                                                           //
// Copyright (c) 2006 - 2007, Peter Jones (AKA Azrael)       //
// All rights reserved.                                      //
//                                                           //
// Redistribution and use with or without modification, are  //
// permitted provided that the following conditions are met: //
//                                                           //
// Redistributions must retain the above copyright notice.   //
// File licence.txt must not be removed from the package.    //
//                                                           //
// Author        : Peter Jones (AKA Azrael)                  //
// E-mail        : Email: p.jones188@btinternet.com          //
// Website       : http://www.gamers-central.com             //
// Support       : http://www.babstats.com                   //
//                                                           //
// File Name     : Preset SQL Strings Include                //
// File Version  : 1.0.4 Standalone                          //
//                                                           //
/////////////////////////////////////////////////////////////*/

/*/////////////////////////////////////////////////////////////
//                                                           //
// Updated Dec 2016 By Novahq.net <scott@novahq.net>         //
// Standalone, PHP 5.6+ Compatible                           //
//                                                           //
/////////////////////////////////////////////////////////////*/

$joSelect["player"] = "$players_table.id          AS id         , 
					   $players_table.name        AS name       , 
                       $players_table.squad       AS squad      , 
					   $players_table.rating      AS rating     , 
					   $players_table.m_rating    AS m_rating   , 
					   $players_table.awards      AS awards     , 
					   $players_table.wpn_awards  AS wpn_awards , 
					   $players_table.veh_awards  AS veh_awards , 
					   $players_table.motm        AS motm ";


$joSelect["stats"] = "$stats_table.team                AS team           , 
					  SUM($stats_table.shotsfired)     AS shotsFired     , 
					  SUM($stats_table.timesHit)       AS timesHit       , 
					  SUM($stats_table.murders)        AS murders        , 
					  SUM($stats_table.kills)          AS kills          , 
					  SUM($stats_table.suicides)       AS suicides       , 
					  SUM($stats_table.suicides)/IF(SUM($stats_table.deaths)=0, 1,  
					  SUM($stats_table.deaths))*100    AS suicidesPer    , 
					  SUM($stats_table.deaths)         AS deaths         , 
					  ROUND(SUM($stats_table.kills)/IF(SUM($stats_table.deaths)=0, 1, 
					  SUM($stats_table.deaths)), 2)    AS ratio          , 
					  SUM($stats_table.medHeal)        AS medHeal        , 
				      SUM($stats_table.medSave)        AS medSave        , 
					  SUM($stats_table.revived)        AS revived        , 
					  SUM($stats_table.flagSaves)      AS flagSaves      , 
					  SUM($stats_table.flagCapt)       AS flagCapt       , 
					  SUM($stats_table.flagPick)       AS flagPick       , 
					  SUM($stats_table.targets)        AS targets        , 
					  SUM($stats_table.pspTakeovers)   AS pspTakeovers   , 
					  SUM($stats_table.headshots)      AS headshots      , 
					  SUM($stats_table.headshots)/IF(SUM($stats_table.kills)=0, 1,  
					  SUM($stats_table.kills))*100     AS headshotsPer   , 
					  ROUND(SUM($stats_table.timesHit)/IF(SUM($stats_table.deaths)=0, 1, 
					  SUM($stats_table.deaths)), 2)    AS avgHdeaths     , 
					  SUM($stats_table.knifings)       AS knifings       , 
					  SUM($stats_table.knifings)/IF(SUM($stats_table.kills)=0, 1,  
					  SUM($stats_table.kills))*100     AS knifingsPer    , 
					  SUM($stats_table.flagCarr)       AS flagCarr       , 
					  SUM($stats_table.score_1)        AS score_1        , 
					  SUM($stats_table.score_2)        AS score_2        , 
					  SUM($stats_table.zoneAtt)        AS zoneAtt        , 
					  SUM($stats_table.zoneDef)        AS zoneDef        , 
					  SUM($stats_table.assists)        AS assists        , 
					  SUM($stats_table.exp)            AS exp            , 
					  SUM($stats_table.tkothTime)      AS tkothTime      , 
					  SUM($stats_table.neutralTime)    AS neutralTime    , 
					  SUM($stats_table.homeTime)       AS homeTime       , 
					  SUM($stats_table.zoneHits)       AS zoneHits       , 
					  SUM($stats_table.campTakeovers)  AS campTakeovers  , 
					  SUM($stats_table.totalTime)      AS totalTime      , 
					  SUM($stats_table.medAttempts)    AS medAttempts    , 
					  SUM($stats_table.sniperkills)    AS sniperkills    , 
					  SUM($stats_table.sniperKills)/IF(SUM($stats_table.kills)=0, 1,  
					  SUM($stats_table.kills))*100     AS sniperKillsPer , 
					  SUM($stats_table.multiKills)     AS multiKills     , 
					  SUM($stats_table.multiKills)/IF(SUM($stats_table.kills)=0, 1,  
					  SUM($stats_table.kills))*100     AS multiKillsPer  , 
					  SUM($stats_table.grating)        AS grating        ,
					  SUM($stats_table.games)          AS games          ,
					  ROUND(SUM($stats_table.wins)/IF(SUM($stats_table.games)=0, 1,  
					  SUM($stats_table.games))*100, 2) AS winPer         , 
					  SUM($stats_table.wins)           AS wins           ,
					  SUM($stats_table.draws)          AS draws          ,
					  SUM($stats_table.games - ($stats_table.wins + 
					  $stats_table.draws))             AS loses          ,
					  MAX($stats_table.last_played)    AS last_played ";

$joSelect["statsm"] = "$stats_m_table.team                AS team           , 
					   SUM($stats_m_table.shotsfired)     AS shotsFired     , 
					   SUM($stats_m_table.timesHit)       AS timesHit       , 
					   SUM($stats_m_table.murders)        AS murders        , 
					   SUM($stats_m_table.kills)          AS kills          , 
					   SUM($stats_m_table.suicides)       AS suicides       , 
					   SUM($stats_m_table.suicides)/IF(SUM($stats_m_table.deaths)=0, 1,  
					   SUM($stats_m_table.deaths))*100    AS suicidesPer    , 
					   SUM($stats_m_table.deaths)         AS deaths         , 
					   ROUND(SUM($stats_m_table.kills)/IF(SUM($stats_m_table.deaths)=0, 1, 
					   SUM($stats_m_table.deaths)), 2)    AS ratio          , 
					   SUM($stats_m_table.medHeal)        AS medHeal        , 
				       SUM($stats_m_table.medSave)        AS medSave        , 
					   SUM($stats_m_table.revived)        AS revived        , 
					   SUM($stats_m_table.flagSaves)      AS flagSaves      , 
					   SUM($stats_m_table.flagCapt)       AS flagCapt       , 
					   SUM($stats_m_table.flagPick)       AS flagPick       , 
					   SUM($stats_m_table.targets)        AS targets        , 
					   SUM($stats_m_table.pspTakeovers)   AS pspTakeovers   , 
					   SUM($stats_m_table.headshots)      AS headshots      , 
					   SUM($stats_m_table.headshots)/IF(SUM($stats_m_table.kills)=0, 1,  
					   SUM($stats_m_table.kills))*100     AS headshotsPer   , 
					   ROUND(SUM($stats_m_table.timesHit)/IF(SUM($stats_m_table.deaths)=0, 1, 
					   SUM($stats_m_table.deaths)), 2)    AS avgHdeaths     , 
					   SUM($stats_m_table.knifings)       AS knifings       , 
					   SUM($stats_m_table.knifings)/IF(SUM($stats_m_table.kills)=0, 1,  
					   SUM($stats_m_table.kills))*100     AS knifingsPer    , 
					   SUM($stats_m_table.flagCarr)       AS flagCarr       , 
					   SUM($stats_m_table.score_1)        AS score_1        , 
					   SUM($stats_m_table.score_2)        AS score_2        , 
					   SUM($stats_m_table.zoneAtt)        AS zoneAtt        , 
					   SUM($stats_m_table.zoneDef)        AS zoneDef        , 
					   SUM($stats_m_table.assists)        AS assists        , 
					   SUM($stats_m_table.exp)            AS exp            , 
					   SUM($stats_m_table.tkothTime)      AS tkothTime      , 
					   SUM($stats_m_table.neutralTime)    AS neutralTime    , 
					   SUM($stats_m_table.homeTime)       AS homeTime       , 
					   SUM($stats_m_table.zoneHits)       AS zoneHits       , 
					   SUM($stats_m_table.campTakeovers)  AS campTakeovers  , 
					   SUM($stats_m_table.totalTime)      AS totalTime      , 
					   SUM($stats_m_table.medAttempts)    AS medAttempts    , 
					   SUM($stats_m_table.sniperkills)    AS sniperkills    , 
					   SUM($stats_m_table.sniperKills)/IF(SUM($stats_m_table.kills)=0, 1,  
					   SUM($stats_m_table.kills))*100     AS sniperKillsPer , 
					   SUM($stats_m_table.multiKills)     AS multiKills     , 
					   SUM($stats_m_table.multiKills)/IF(SUM($stats_m_table.kills)=0, 1,  
					   SUM($stats_m_table.kills))*100     AS multiKillsPer  , 
					   SUM($stats_m_table.grating)        AS grating        ,
					   SUM($stats_m_table.games)          AS games          ,
					   ROUND(SUM($stats_m_table.wins)/IF(SUM($stats_m_table.games)=0, 1,  
					   SUM($stats_m_table.games))*100, 2) AS winPer         , 
					   SUM($stats_m_table.wins)           AS wins           ,
					   SUM($stats_m_table.draws)          AS draws          ,
					   SUM($stats_m_table.games - ($stats_m_table.wins + 
					   $stats_m_table.draws))             AS loses          ,
					   MAX($stats_m_table.last_played)    AS last_played ";

$joSelect["weapon"] = "$weapons_table.id   AS w_id   , 
                       $weapons_table.name AS w_name ";

					  
$joSelect["weaponstats"] = "SUM($weaponstats_table.shotsfired)          AS w_shotsFired     , 
						    SUM($weaponstats_table.timesHit)            AS w_timesHit       , 
						    SUM($weaponstats_table.murders)             AS w_murders        , 
						    SUM($weaponstats_table.kills)               AS w_kills          , 
							ROUND(SUM($weaponstats_table.kills)/IF(SUM($weaponstats_table.shotsFired)=0, 1, 
			                SUM($weaponstats_table.shotsFired))*100, 2) AS w_accuracy       ,
						    SUM($weaponstats_table.suicides)            AS w_suicides       , 
							SUM($weaponstats_table.suicides)/IF(SUM($weaponstats_table.deaths)=0, 1,  
					  		SUM($weaponstats_table.deaths))*100         AS w_suicidesPer    ,  
						    SUM($weaponstats_table.deaths)              AS w_deaths         , 
						    ROUND(SUM($weaponstats_table.kills)/IF(SUM($weaponstats_table.deaths)=0, 1, 
						    SUM($weaponstats_table.deaths)), 2)         AS w_ratio          , 
						    SUM($weaponstats_table.medHeal)             AS w_medHeal        , 
						    SUM($weaponstats_table.medSave)             AS w_medSave        , 
						    SUM($weaponstats_table.revived)             AS w_revived        , 
						    SUM($weaponstats_table.flagSaves)           AS w_flagSaves      , 
						    SUM($weaponstats_table.flagCapt)            AS w_flagCapt       , 
						    SUM($weaponstats_table.flagPick)            AS w_flagPick       , 
						    SUM($weaponstats_table.targets)             AS w_targets        , 
						    SUM($weaponstats_table.pspTakeovers)        AS w_pspTakeovers   , 
						    SUM($weaponstats_table.headshots)           AS w_headshots      , 
							SUM($weaponstats_table.headshots)/IF(SUM($weaponstats_table.kills)=0, 1,  
					 		SUM($weaponstats_table.kills))*100          AS w_headshotsPer   ,  
						    SUM($weaponstats_table.timesHit)/IF(SUM($weaponstats_table.deaths)=0, 1, 
						    SUM($weaponstats_table.deaths))             AS w_avgHdeaths     , 
						    SUM($weaponstats_table.knifings)            AS w_knifings       , 
						    SUM($weaponstats_table.flagCarr)            AS w_flagCarr       , 
						    SUM($weaponstats_table.score_1)             AS w_score_1        , 
						    SUM($weaponstats_table.score_2)             AS w_score_2        , 
						    SUM($weaponstats_table.zoneAtt)             AS w_zoneAtt        , 
						    SUM($weaponstats_table.zoneDef)             AS w_zoneDef        , 
						    SUM($weaponstats_table.assists)             AS w_assists        , 
						    SUM($weaponstats_table.tkothTime)           AS w_tkothTime      , 
						    SUM($weaponstats_table.neutralTime)         AS w_neutralTime    , 
						    SUM($weaponstats_table.homeTime)            AS w_homeTime       , 
						    SUM($weaponstats_table.zoneHits)            AS w_zoneHits       , 
						    SUM($weaponstats_table.campTakeovers)       AS w_campTakeovers  , 
						    SUM($weaponstats_table.totalTime)           AS w_totalTime      , 
						    SUM($weaponstats_table.medAttempts)         AS w_medAttempts    , 
						    SUM($weaponstats_table.sniperkills)         AS w_sniperkills    ,
							SUM($weaponstats_table.multiKills)/IF(SUM($weaponstats_table.kills)=0, 1,  
					  		SUM($weaponstats_table.kills))*100          AS w_multiKillsPer  ,  
						    SUM($weaponstats_table.multiKills)          AS w_multiKills     ";
							
$joSelect["weaponstatsm"] = "SUM($weaponstats_m_table.shotsfired)          AS w_shotsFired     , 
						     SUM($weaponstats_m_table.timesHit)            AS w_timesHit       , 
						     SUM($weaponstats_m_table.murders)             AS w_murders        , 
						     SUM($weaponstats_m_table.kills)               AS w_kills          , 
							 ROUND(SUM($weaponstats_m_table.kills)/IF(SUM($weaponstats_m_table.shotsFired)=0, 1, 
			                 SUM($weaponstats_m_table.shotsFired))*100, 2) AS w_accuracy       ,
						     SUM($weaponstats_m_table.suicides)            AS w_suicides       , 
							 SUM($weaponstats_m_table.suicides)/IF(SUM($weaponstats_m_table.deaths)=0, 1,  
					  		 SUM($weaponstats_m_table.deaths))*100         AS w_suicidesPer    ,  
						     SUM($weaponstats_m_table.deaths)              AS w_deaths         , 
						     ROUND(SUM($weaponstats_m_table.kills)/IF(SUM($weaponstats_m_table.deaths)=0, 1, 
						     SUM($weaponstats_m_table.deaths)), 2)         AS w_ratio          , 
						     SUM($weaponstats_m_table.medHeal)             AS w_medHeal        , 
						     SUM($weaponstats_m_table.medSave)             AS w_medSave        , 
						     SUM($weaponstats_m_table.revived)             AS w_revived        , 
						     SUM($weaponstats_m_table.flagSaves)           AS w_flagSaves      , 
						     SUM($weaponstats_m_table.flagCapt)            AS w_flagCapt       , 
						     SUM($weaponstats_m_table.flagPick)            AS w_flagPick       , 
						     SUM($weaponstats_m_table.targets)             AS w_targets        , 
						     SUM($weaponstats_m_table.pspTakeovers)        AS w_pspTakeovers   , 
						     SUM($weaponstats_m_table.headshots)           AS w_headshots      , 
							 SUM($weaponstats_m_table.headshots)/IF(SUM($weaponstats_m_table.kills)=0, 1,  
					 		 SUM($weaponstats_m_table.kills))*100          AS w_headshotsPer   ,  
						     SUM($weaponstats_m_table.timesHit)/IF(SUM($weaponstats_m_table.deaths)=0, 1, 
						     SUM($weaponstats_m_table.deaths))             AS w_avgHdeaths     , 
						     SUM($weaponstats_m_table.knifings)            AS w_knifings       , 
						     SUM($weaponstats_m_table.flagCarr)            AS w_flagCarr       , 
						     SUM($weaponstats_m_table.score_1)             AS w_score_1        , 
						     SUM($weaponstats_m_table.score_2)             AS w_score_2        , 
						     SUM($weaponstats_m_table.zoneAtt)             AS w_zoneAtt        , 
						     SUM($weaponstats_m_table.zoneDef)             AS w_zoneDef        , 
						     SUM($weaponstats_m_table.assists)             AS w_assists        , 
						     SUM($weaponstats_m_table.tkothTime)           AS w_tkothTime      , 
						     SUM($weaponstats_m_table.neutralTime)         AS w_neutralTime    , 
						     SUM($weaponstats_m_table.homeTime)            AS w_homeTime       , 
						     SUM($weaponstats_m_table.zoneHits)            AS w_zoneHits       , 
						     SUM($weaponstats_m_table.campTakeovers)       AS w_campTakeovers  , 
						     SUM($weaponstats_m_table.totalTime)           AS w_totalTime      , 
						     SUM($weaponstats_m_table.medAttempts)         AS w_medAttempts    , 
						     SUM($weaponstats_m_table.sniperkills)         AS w_sniperkills    ,
							 SUM($weaponstats_m_table.multiKills)/IF(SUM($weaponstats_m_table.kills)=0, 1,  
					  		 SUM($weaponstats_m_table.kills))*100          AS w_multiKillsPer  ,  
						     SUM($weaponstats_m_table.multiKills)          AS w_multiKills     ";
							
							
$joSelect["vehicle"] = "$vehicles_table.id  AS v_id   , 
                        $vehicles_table.name AS v_name ";

				  
$joSelect["vehiclestats"] = "SUM($vehiclestats_table.shotsfired)          AS v_shotsFired     , 
						     SUM($vehiclestats_table.timesHit)            AS v_timesHit       , 
						     SUM($vehiclestats_table.murders)             AS v_murders        , 
						     SUM($vehiclestats_table.kills)               AS v_kills          , 
						 	 ROUND(SUM($vehiclestats_table.kills)/IF(SUM($vehiclestats_table.shotsFired)=0, 1, 
			                 SUM($vehiclestats_table.shotsFired))*100, 2) AS v_accuracy       ,
						     SUM($vehiclestats_table.suicides)            AS v_suicides       , 
							 SUM($vehiclestats_table.suicides)/IF(SUM($vehiclestats_table.deaths)=0, 1,  
					  		 SUM($vehiclestats_table.deaths))*100         AS v_suicidesPer    ,
						     SUM($vehiclestats_table.deaths)              AS v_deaths         , 
						     ROUND(SUM($vehiclestats_table.kills)/IF(SUM($vehiclestats_table.deaths)=0, 1, 
						     SUM($vehiclestats_table.deaths)), 2)         AS v_ratio          , 
						     SUM($vehiclestats_table.medHeal)             AS v_medHeal        , 
						     SUM($vehiclestats_table.medSave)             AS v_medSave        , 
						     SUM($vehiclestats_table.revived)             AS v_revived        , 
						     SUM($vehiclestats_table.flagSaves)           AS v_flagSaves      , 
						     SUM($vehiclestats_table.flagCapt)            AS v_flagCapt       , 
						     SUM($vehiclestats_table.flagPick)            AS v_flagPick       , 
						     SUM($vehiclestats_table.targets)             AS v_targets        , 
						     SUM($vehiclestats_table.pspTakeovers)        AS v_pspTakeovers   , 
						     SUM($vehiclestats_table.headshots)           AS v_headshots      ,  
						     SUM($vehiclestats_table.headshots)/IF(SUM($vehiclestats_table.kills)=0, 1,  
					 		 SUM($vehiclestats_table.kills))*100          AS v_headshotsPer   ,
							 SUM($vehiclestats_table.timesHit)/IF(SUM($vehiclestats_table.deaths)=0, 1, 
						     SUM($vehiclestats_table.deaths))             AS v_avgHdeaths     , 
						     SUM($vehiclestats_table.knifings)            AS v_knifings       , 
						     SUM($vehiclestats_table.flagCarr)            AS v_flagCarr       , 
						     SUM($vehiclestats_table.score_1)             AS v_score_1        , 
						     SUM($vehiclestats_table.score_2)             AS v_score_2        , 
						     SUM($vehiclestats_table.zoneAtt)             AS v_zoneAtt        , 
						     SUM($vehiclestats_table.zoneDef)             AS v_zoneDef        , 
						     SUM($vehiclestats_table.assists)             AS v_assists        , 
						     SUM($vehiclestats_table.tkothTime)           AS v_tkothTime      , 
						     SUM($vehiclestats_table.neutralTime)         AS v_neutralTime    , 
						     SUM($vehiclestats_table.homeTime)            AS v_homeTime       , 
						     SUM($vehiclestats_table.zoneHits)            AS v_zoneHits       , 
						     SUM($vehiclestats_table.campTakeovers)       AS v_campTakeovers  , 
						     SUM($vehiclestats_table.totalTime)           AS v_totalTime      , 
						     SUM($vehiclestats_table.medAttempts)         AS v_medAttempts    , 
						     SUM($vehiclestats_table.sniperkills)         AS v_sniperkills    ,  
							 SUM($vehiclestats_table.multiKills)/IF(SUM($vehiclestats_table.kills)=0, 1,  
					  		 SUM($vehiclestats_table.kills))*100          AS v_multiKillsPer  , 
						     SUM($vehiclestats_table.multiKills)          AS v_multiKills     ";
							
$joSelect["vehiclestatsm"] = "SUM($vehiclestats_m_table.shotsfired)          AS v_shotsFired     , 
						      SUM($vehiclestats_m_table.timesHit)            AS v_timesHit       , 
						      SUM($vehiclestats_m_table.murders)             AS v_murders        , 
						      SUM($vehiclestats_m_table.kills)               AS v_kills          , 
						 	  ROUND(SUM($vehiclestats_m_table.kills)/IF(SUM($vehiclestats_m_table.shotsFired)=0, 1, 
			                  SUM($vehiclestats_m_table.shotsFired))*100, 2) AS v_accuracy       ,
						      SUM($vehiclestats_m_table.suicides)            AS v_suicides       , 
							  SUM($vehiclestats_m_table.suicides)/IF(SUM($vehiclestats_m_table.deaths)=0, 1,  
					  		  SUM($vehiclestats_m_table.deaths))*100         AS v_suicidesPer    ,
						      SUM($vehiclestats_m_table.deaths)              AS v_deaths         , 
						      ROUND(SUM($vehiclestats_m_table.kills)/IF(SUM($vehiclestats_m_table.deaths)=0, 1, 
						      SUM($vehiclestats_m_table.deaths)), 2)         AS v_ratio          , 
						      SUM($vehiclestats_m_table.medHeal)             AS v_medHeal        , 
						      SUM($vehiclestats_m_table.medSave)             AS v_medSave        , 
						      SUM($vehiclestats_m_table.revived)             AS v_revived        , 
						      SUM($vehiclestats_m_table.flagSaves)           AS v_flagSaves      , 
						      SUM($vehiclestats_m_table.flagCapt)            AS v_flagCapt       , 
						      SUM($vehiclestats_m_table.flagPick)            AS v_flagPick       , 
						      SUM($vehiclestats_m_table.targets)             AS v_targets        , 
						      SUM($vehiclestats_m_table.pspTakeovers)        AS v_pspTakeovers   , 
						      SUM($vehiclestats_m_table.headshots)           AS v_headshots      ,  
						      SUM($vehiclestats_m_table.headshots)/IF(SUM($vehiclestats_m_table.kills)=0, 1,  
					 		  SUM($vehiclestats_m_table.kills))*100          AS v_headshotsPer   ,
							  SUM($vehiclestats_m_table.timesHit)/IF(SUM($vehiclestats_m_table.deaths)=0, 1, 
						      SUM($vehiclestats_m_table.deaths))             AS v_avgHdeaths     , 
						      SUM($vehiclestats_m_table.knifings)            AS v_knifings       , 
						      SUM($vehiclestats_m_table.flagCarr)            AS v_flagCarr       , 
						      SUM($vehiclestats_m_table.score_1)             AS v_score_1        , 
						      SUM($vehiclestats_m_table.score_2)             AS v_score_2        , 
						      SUM($vehiclestats_m_table.zoneAtt)             AS v_zoneAtt        , 
						      SUM($vehiclestats_m_table.zoneDef)             AS v_zoneDef        , 
						      SUM($vehiclestats_m_table.assists)             AS v_assists        , 
						      SUM($vehiclestats_m_table.tkothTime)           AS v_tkothTime      , 
						      SUM($vehiclestats_m_table.neutralTime)         AS v_neutralTime    , 
						      SUM($vehiclestats_m_table.homeTime)            AS v_homeTime       , 
						      SUM($vehiclestats_m_table.zoneHits)            AS v_zoneHits       , 
						      SUM($vehiclestats_m_table.campTakeovers)       AS v_campTakeovers  , 
						      SUM($vehiclestats_m_table.totalTime)           AS v_totalTime      , 
						      SUM($vehiclestats_m_table.medAttempts)         AS v_medAttempts    , 
						      SUM($vehiclestats_m_table.sniperkills)         AS v_sniperkills    ,  
							  SUM($vehiclestats_m_table.multiKills)/IF(SUM($vehiclestats_m_table.kills)=0, 1,  
					  		  SUM($vehiclestats_m_table.kills))*100          AS v_multiKillsPer  , 
						      SUM($vehiclestats_m_table.multiKills)          AS v_multiKills     ";
							
$joSelect["map"] = "$maps_table.id    AS m_id    , 
                    $maps_table.name  AS m_name  ,
					$maps_table.image AS m_image ";

				  
$joSelect["mapstats"] = "SUM($mapstats_table.murders)                  AS m_murders         , 
						 ROUND(SUM($mapstats_table.murders)/IF(SUM($mapstats_table.games)=0, 1, 
						 SUM($mapstats_table.games)), 2)               AS m_murdersPer      , 
						 SUM($mapstats_table.kills)                    AS m_kills           , 
						 ROUND(SUM($mapstats_table.kills)/IF(SUM($mapstats_table.games)=0, 1, 
						 SUM($mapstats_table.games)), 2)               AS m_killsPer        ,
						 SUM($mapstats_table.suicides)                 AS m_suicides        , 
						 ROUND(SUM($mapstats_table.suicides)/IF(SUM($mapstats_table.games)=0, 1, 
						 SUM($mapstats_table.games)), 2)               AS m_suicidesPer     ,
						 SUM($mapstats_table.deaths)                   AS m_deaths          , 
						 ROUND(SUM($mapstats_table.deaths)/IF(SUM($mapstats_table.games)=0, 1, 
						 SUM($mapstats_table.games)), 2)               AS m_deathsPer       ,
						 ROUND(SUM($mapstats_table.kills)/IF(SUM($mapstats_table.deaths)=0, 1, 
						 SUM($mapstats_table.deaths)), 2)              AS m_ratio           , 
						 SUM($mapstats_table.headshots)                AS m_headshots       ,
						 ROUND(SUM($mapstats_table.headshots)/IF(SUM($mapstats_table.games)=0, 1, 
						 SUM($mapstats_table.games)), 2)               AS m_headshotsPer    ,
						 SUM($mapstats_table.sniperkills)              AS m_sniperKills     ,
						 ROUND(SUM($mapstats_table.sniperkills)/IF(SUM($mapstats_table.games)=0, 1, 
						 SUM($mapstats_table.games)), 2)               AS m_sniperKillsPer  ,
						 SUM($mapstats_table.knifings)                 AS m_knifings        ,
						 ROUND(SUM($mapstats_table.knifings)/IF(SUM($mapstats_table.games)=0, 1, 
						 SUM($mapstats_table.games)), 2)               AS m_knifingsPer     ,
						 SUM($mapstats_table.multiKills)               AS m_multiKills      ,
						 ROUND(SUM($mapstats_table.multiKills)/IF(SUM($mapstats_table.games)=0, 1, 
						 SUM($mapstats_table.games)), 2)               AS m_multiKillsPer   ,
						 SUM($mapstats_table.assists)                  AS m_assists         ,
						 ROUND(SUM($mapstats_table.assists)/IF(SUM($mapstats_table.games)=0, 1, 
						 SUM($mapstats_table.games)), 2)               AS m_assistsPer      ,
						 SUM($mapstats_table.games)                    AS m_games           ,
						 SUM($mapstats_table.wins)                     AS m_wins            ,
						 SUM($mapstats_table.draws)                    AS m_draws           ,
			 			 ROUND(SUM($mapstats_table.wins)/IF(SUM($mapstats_table.games)=0, 1, 
			 			 SUM($mapstats_table.games))*100, 2)           AS m_winPer          , 
						 SUM($mapstats_table.totalTime)                AS m_totalTime       ";
						 
$joSelect["mapstatsm"] = "SUM($mapstats_m_table.murders)                  AS m_murders         , 
						  ROUND(SUM($mapstats_m_table.murders)/IF(SUM($mapstats_m_table.games)=0, 1, 
						  SUM($mapstats_m_table.games)), 2)               AS m_murdersPer      , 
						  SUM($mapstats_m_table.kills)                    AS m_kills           , 
						  ROUND(SUM($mapstats_m_table.kills)/IF(SUM($mapstats_m_table.games)=0, 1, 
						  SUM($mapstats_m_table.games)), 2)               AS m_killsPer        ,
						  SUM($mapstats_m_table.suicides)                 AS m_suicides        , 
						  ROUND(SUM($mapstats_m_table.suicides)/IF(SUM($mapstats_m_table.games)=0, 1, 
						  SUM($mapstats_m_table.games)), 2)               AS m_suicidesPer     ,
						  SUM($mapstats_m_table.deaths)                   AS m_deaths          , 
						  ROUND(SUM($mapstats_m_table.deaths)/IF(SUM($mapstats_m_table.games)=0, 1, 
						  SUM($mapstats_m_table.games)), 2)               AS m_deathsPer       ,
						  ROUND(SUM($mapstats_m_table.kills)/IF(SUM($mapstats_m_table.deaths)=0, 1, 
						  SUM($mapstats_m_table.deaths)), 2)              AS m_ratio           , 
						  SUM($mapstats_m_table.headshots)                AS m_headshots       ,
						  ROUND(SUM($mapstats_m_table.headshots)/IF(SUM($mapstats_m_table.games)=0, 1, 
						  SUM($mapstats_m_table.games)), 2)               AS m_headshotsPer    ,
						  SUM($mapstats_m_table.sniperkills)              AS m_sniperKills     ,
						  ROUND(SUM($mapstats_m_table.sniperkills)/IF(SUM($mapstats_m_table.games)=0, 1, 
						  SUM($mapstats_m_table.games)), 2)               AS m_sniperKillsPer  ,
						  SUM($mapstats_m_table.knifings)                 AS m_knifings        ,
						  ROUND(SUM($mapstats_m_table.knifings)/IF(SUM($mapstats_m_table.games)=0, 1, 
						  SUM($mapstats_m_table.games)), 2)               AS m_knifingsPer     ,
						  SUM($mapstats_m_table.multiKills)               AS m_multiKills      ,
						  ROUND(SUM($mapstats_m_table.multiKills)/IF(SUM($mapstats_m_table.games)=0, 1, 
						  SUM($mapstats_m_table.games)), 2)               AS m_multiKillsPer   ,
						  SUM($mapstats_m_table.assists)                  AS m_assists         ,
						  ROUND(SUM($mapstats_m_table.assists)/IF(SUM($mapstats_m_table.games)=0, 1, 
						  SUM($mapstats_m_table.games)), 2)               AS m_assistsPer      ,
						  SUM($mapstats_m_table.games)                    AS m_games           ,
						  SUM($mapstats_m_table.wins)                     AS m_wins            ,
						  SUM($mapstats_m_table.draws)                    AS m_draws           ,
			 			  ROUND(SUM($mapstats_m_table.wins)/IF(SUM($mapstats_m_table.games)=0, 1, 
			 			  SUM($mapstats_m_table.games))*100, 2)           AS m_winPer          , 
						  SUM($mapstats_m_table.totalTime)                AS m_totalTime       ";