<?php
/*/////////////////////////////////////////////////////////////
//                                                           //
// JOStats is a product of Bab.stats                         //
//                                                           //
// Copyright (c) 2006 - 2007, Peter Jones (AKA Azrael)       //
// All rights reserved.                                      //
//                                                           //
// Redistribution and use with or without modification, are  //
// permitted provided that the following conditions are met: //
//                                                           //
// Redistributions must retain the above copyright notice.   //
// File licence.txt must not be removed from the package.    //
//                                                           //
// Author        : Peter Jones (AKA Azrael)                  //
// E-mail        : Email: p.jones188@btinternet.com          //
// Website       : http://www.messiahgamingtools.com         //
// Support       : http://www.babstats.com                   //
//                                                           //
// File Name     : Vehicles Presets Include                  //
// File Version  : 1.1.0 PHP-Nuke                            //
//                                                           //
/////////////////////////////////////////////////////////////*/

/*/////////////////////////////////////////////////////////////
//                                                           //
// Updated Dec 2016 By Novahq.net <scott@novahq.net>         //
// Standalone, PHP 5.6+ Compatible                           //
//                                                           //
/////////////////////////////////////////////////////////////*/

$veh_attach = array(
	1 => "Passenger"   ,
	2 => "Driver/Pilot",
	3 => "Gunner"
);

$veh_common = array(
	"a-10"           => "a10.gif",
	"ah-6"           => "ah6j.gif", 
	"ah-64"          => "ah64.gif", 
	"ambula"         => "truck.gif",
	"apache"         => "ah64.gif",
	"armored jeep"   => "hummer.gif", 
	"armored mobile" => "abrams.gif", 
	"assault boat"   => "apb.gif", 
	"attack heli"    => "ah64.gif",
	"attack veh"     => "jeep50.gif", 
	"atv"            => "atv.gif",
	"battle helo"    => "bhelo.gif",
	"bike"           => "bike.gif", 
	"bird"           => "ah6j.gif", 
	"blimp"          => "blimp.gif",
	"bmd"            => "bmd.gif", 
	"brdm"           => "brdm.gif",
	"btr"            => "btr.gif", 
	"buggy"          => "buggy.gif", 
	"bus"            => "cbus.gif",
	"cannon boat"    => "cboat.gif",
	"cargo"          => "uncargo.gif",
	"carpet"         => "carp.gif",
	"cessna"         => "cessn.gif",
	"challenger"     => "abrams.gif",
	"chinook"        => "chinook.gif", 
	"civilian boat"  => "boat1.gif",
	"coast guard"    => "cgurd.gif",
	"cobra"          => "cobra.gif",
	"cruiser"        => "miscr.gif",
	"cycle"          => "bike.gif", 
	"dunebeetle"     => "dbeetle.gif",
	"ee-9"           => "ee9.gif", 
	"european car"   => "eurocar.gif",
	"fenn"           => "fenn.gif",
	"firetruck"      => "frtru.gif",
	"flaming chevy"  => "chev.gif",
	"fork"           => "fork.gif", 
	"fuchs"          => "brdm.gif",
	"fuel"           => "fuel.gif",
	"gaz"            => "gaz.gif",
	"gepa"           => "gepa.gif",
	"glider"         => "hang.gif",
	"go-kart"        => "goka.gif",
	"guaz"           => "jeep50.gif", 
	"halftr"         => "suva.gif", 
	"havoc"          => "ah64.gif",
	"harve"          => "harve.gif",
	"hawk"           => "blackhawk.gif", 
	"hcss"           => "hcss.gif",
	"hemtt"          => "hemtt.gif",
	"higgins"        => "hig.gif",
	"hind"           => "hind.gif",
	"hot air"        => "hair.gif",
	"hover plane"    => "hovr.gif",
	"huey"           => "bhelo.gif",
	"hummer"         => "hummer.gif", 
	"humv"           => "hummer.gif", 
	"howitzer"       => "howitzer.gif",
	"impala"         => "impa.gif",
	"indo"           => "aab.gif", 
	"inflatable"     => "inflatable.gif",
	"jeep"           => "jeep.gif",
	"jet pack"       => "jetp.gif",
	"ka-27"          => "helix.gif",
	"ka-52"          => "ka.gif", 
	"lcac"           => "lcac.gif", 
	"lcm"            => "lcac.gif",
	"leclerc"        => "abrams.gif",
	"leopard"        => "abrams.gif",
	"lincoln"        => "linc.gif",
	"lynx"           => "lynx.gif",
	"m113"           => "m163.gif",
	"m163"           => "m163.gif",
	"m1a1"           => "abrams.gif", 
	"mard"           => "mard.gif",
	"mark"           => "markv.gif", 
	"mig-29"         => "mig29.gif",
	"military truck" => "mtru.gif",
	"minivan"        => "suva.gif",
	"miniyatch"      => "miya.gif",
	"mlrs"           => "mard.gif", 
	"mobile aa"      => "bmd.gif",
	"monster truck"  => "monstr.gif",
	"mv-22"          => "mv22.gif",
	"nb0"            => "nbo.gif", 
	"oh58"           => "oh58.gif", 
	"p-51"           => "p51m.gif", 
	"patrol"         => "apb.gif", 
	"pavlow"         => "pavlow.gif",
	"pickup"         => "pickup50.gif",
	"pirate ship"    => "pship.gif",
	"porsche"        => "porsche.gif",
	"puma"           => "puma.gif", 
	"quad"           => "quad.gif",
	"rapi"           => "mard.gif",
	"rig"            => "rig.gif",
	"rola"           => "mard.gif",
	"sa-13"          => "sa13.gif",
	"scooter"        => "sscooter.gif",
	"scud"           => "scud.gif", 
	"ski"            => "jetski.gif",
	"small pirate"   => "sboat.gif",
	"speed boat"     => "speedb.gif",
	"speedboat"      => "spdb.gif",
	"stryker"        => "stryker.gif",
	"stuka"          => "stuka.gif", 
	"su-25"          => "su25.gif",
	"suv"            => "jeep50.gif", 
	"swamp boat"     => "swamp.gif",
	"t-80"           => "t80u.gif", 
	"t80"            => "t80u.gif", 
	"t90"            => "t80u.gif",
	"taxi"           => "taxi.gif", 
	"technical"      => "technical.gif", 
	"tiger at"       => "ah64.gif", 
	"tractor"        => "trac.gif",
	"transport"      => "truck.gif",
	"trolley"        => "trol.gif",
	"tung"           => "tungu.gif", 
	"vab"            => "vab.gif", 
	"vbl"            => "vbl.gif",
	"viper"          => "ah64.gif", 
	"warr"           => "warr.gif",
	"wiesel"         => "stryker.gif",
	"willy"          => "jeep.gif",
	"wodden boat"    => "wboat.gif",
	"zodiac"         => "zodiac.gif", 
	"zpu"            => "zpu.gif", 
	"zsu"            => "zsu.gif",
);

$veh_img = array(
	"KA-52"                   => "ka.gif"          ,
	"AH-64A"                  => "ah64.gif"        ,
	"M1A1 Abrams"             => "abrams.gif"      ,
	"T-80U"                   => "t80u.gif"        ,
	"Fuel Truck"              => "fuel.gif"        ,
	"Motorbike"               => "bike.gif"        ,
	"Civilian Taxi"           => "taxi.gif"        ,
	"Buggy"                   => "buggy.gif"       ,
	"AH-6J Little Bird"       => "ah6j.gif"        ,
	"AH-6J (miniguns)"        => "ah6jm.gif"       ,
	"AH-6J (rockets)"         => "ah6jr.gif"       ,
	"Chinook (armory)"        => "chinook.gif"     ,
	"Chinook"                 => "chinook.gif"     ,
	"SA 330 Super Puma"       => "puma.gif"        ,
	"ATV"                     => "atv.gif"         ,
	"Armored Jeep (50 Cal)"   => "jeep50.gif"      ,
	"Armored Jeep (MK-19)"    => "jeepmk19.gif"    ,
	"Zodiac"                  => "zodiac.gif"      ,
	"Zodiac (M60)"            => "zodiacm60.gif"   ,
	"Military Truck"          => "truck.gif"       ,
	"Military Truck (armory)" => "trucka.gif"      ,
	"LCAC"                    => "lcac.gif"        ,
	"AAV (50 Cal)"            => "aav50.gif"       ,
	"AAV (MK-19)"             => "aavmk19.gif"     ,
	"Mark V"                  => "markv.gif"       ,
	"Amphibious Assault Boat" => "aab.gif"         ,
	"BTR"                     => "btr.gif"         ,
	"Stryker"                 => "stryker.gif"     ,
	"MI-26 Halo"              => "halo.gif"        ,
	"NBO-105"                 => "nbo.gif"         ,
	"NBO-105 (miniguns)"      => "nbom.gif"        ,
	"NBO-105 (rockets)"       => "nbor.gif"        ,
	"NBO-105 (sidewinders)"   => "nbor.gif"        ,
	"Armored Patrol Boat"     => "apb.gif"         ,
	"MH-60 Blackhawk"         => "blackhawk.gif"   ,
	"Civilian Boat"           => "boat1.gif"       ,
	"Hummer"                  => "hummer.gif"      ,
	"Hummer (avenger)"        => "hummer.gif"      ,
	"Hummer (50 Cal)"         => "hummer.gif"      ,
	"Hummer (MK-19)"          => "hummer.gif"      ,
	"Recon Stryker"           => "stryker.gif"     ,
	"Stryker Transport"       => "stryker.gif"     ,
	"Armored Jeep"            => "aav50.gif"       ,
	"Mobile PSP Boat"         => "lcac.gif"        ,
	"Mark VI"                 => "markv.gif"       ,
	"Mark VII"                => "markv.gif"       ,
	"Mobile PSP"              => "abrams.gif"      ,
	"KA-52 (hellfires)"       => "ka.gif"          ,
	"KA-52 (hydras)"          => "ka.gif"          ,
	"AH-64A (hellfires)"      => "ah64.gif"        ,
	"Assault Boat VI"         => "aab.gif"         ,
	"Assault Boat VII"        => "aab.gif"         ,
	"AH-6J (sidewinders)"     => "ah6jr.gif"       ,
	"AH-6J (hellfires)"       => "ah6jr.gif"       ,
	"AH-6J (medivac)"         => "ah6j.gif"        ,
	"Nuke Howitzer"           => "howitzer.gif"    ,
	"Snow Scooter"            => "sscooter.gif"    ,
	"Cannon Boat"             => "cboat.gif"       ,
	"Willy Jeep (50 Cal)"     => "jeep.gif"        ,
    "Willy Jeep"              => "jeep.gif"        ,
	"Jet Ski (miniguns)"      => "jetski.gif"      ,
	"OH58 Kiowa"              => "oh58.gif"        ,
	"OH58 OH58 (miniguns)"    => "oh58m.gif"       ,
	"OH58 OH58 (rockets)"     => "oh58r.gif"       ,
	"Inflatable Boat"         => "inflatable.gif"  ,
	"Speed Boat"              => "speedb.gif"      ,
	"OH58 (rockets/50Cal)"    => "oh58r.gif"       ,
	"Civilian Bus"            => "cbus.gif"        ,
    "VW Bus (armory)"         => "vwbus.gif"       ,
	"Wooden Boat (50 Cal)"    => "wboat.gif"       ,
	"Scrappy Jeep"            => "scrappy.gif"     ,
	"Technical"               => "technical.gif"   ,
	"European Car"            => "eurocar.gif"     ,
	"Pickup Truck (50 Cal)"   => "pickup50.gif"    ,
	"Technical (50 Cal)"      => "technical50.gif" ,
	"UN Cargo Truck"          => "uncargo.gif"     ,
	"Chemical Cargo Truck"    => "chemical.gif"    ,
	"Technical (EM Cannon)"   => "technicalem.gif" ,
	"VBL Vehicle (50 Cal)"    => "vbl.gif"         ,
	"PAVLOW"                  => "pavlow.gif"      ,
	"Patrol Boat"             => "patrol.gif"      ,
	"AH-6J (rockets/m60)"     => "ah6jr.gif"       ,
	"Howitzer"                => "howitzer.gif"    
);