<?php
/*/////////////////////////////////////////////////////////////
//                                                           //
// JOStats is a product of Bab.stats                         //
//                                                           //
// Copyright (c) 2006 - 2007, Peter Jones (AKA Azrael)       //
// All rights reserved.                                      //
//                                                           //
// Redistribution and use with or without modification, are  //
// permitted provided that the following conditions are met: //
//                                                           //
// Redistributions must retain the above copyright notice.   //
// File licence.txt must not be removed from the package.    //
//                                                           //
// Author        : Peter Jones (AKA Azrael)                  //
// E-mail        : Email: p.jones188@btinternet.com          //
// Website       : http://www.gamers-central.com             //
// Support       : http://www.babstats.com                   //
//                                                           //
// File Name     : Weapons Presets Include                   //
// File Version  : 1.1.3 Standalone                          //
//                                                           //
/////////////////////////////////////////////////////////////*/

/*/////////////////////////////////////////////////////////////
//                                                           //
// Updated Dec 2016 By Novahq.net <scott@novahq.net>         //
// Standalone, PHP 5.6+ Compatible                           //
//                                                           //
/////////////////////////////////////////////////////////////*/

$wpn_no_kills = array("Green Smoke", "Grey Smoke", "Flash Bang", "Med Pack", "Blue Smoke", "Yellow Smoke", "Red Smoke", "Detonator", 
                      "Target Designator", "Green Smoke", "Grey Smoke", "Medic Pack", "Thermal Vision Goggles", "Flaregun", "Smoke Signal", 
					  "Commander Smoke", "Smoke Grenade", "LLDR (IR)", "LLDR", "Smoke Grenade(G)", "Smoke Grenade(R)");

$wpn_img = array(
    ".357 Magnum"             => "magnum.gif"     ,
    ".50 Cal"                 => "cal.gif"        ,
    ".50 Cal Artillery"       => "cal.gif"        ,
    "105 MM Cannon"           => "veh125.gif"     ,
    "12.5 MM"                 => "12_5mm.gif"     ,
    "120 MM Cannon"           => "veh120.gif"     ,
    "120 MM Mortar"           => "mortar.gif"     ,
    "120mm Cannon"            => "veh120.gif"     ,
    "125 MM Cannon"           => "veh125.gif"     ,
    "125mm Cannon"            => "veh125.gif"     ,
    "14.5mm Cannons"          => "cal.gif"        ,
    "155 MM Howitzer"         => "155how.gif"     ,
    "20 MM MK"                => "cannon30mm.gif" ,
    "20MM"                    => "20mm.gif"       ,
    "20mm Vulcan"             => "cal.gif"        ,
    "227mm MLRS Launcher"     => "rocket.gif"     ,
    "23 MM Cannon"            => "minigun.gif"    ,
    "23mm Cannon"             => "minigun.gif"    ,
    "30 Cal Machinegun"       => "30cal.gif"      ,
    "30 MM Cannon"            => "cannon30mm.gif" ,
    "50 Cal"                  => "cal.gif"        ,
    "50 Cal Machinegun"       => "cal.gif"        ,
    "50 Cal Tripod"           => "cal.gif"        ,
    "88 Flak Cannon"          => "artillery.gif"  ,
    "AGS-17 Grenade Launcher" => "glauncher.gif"  ,
    "AK103 GP-30 Auto"        => "ak47he.gif"     ,
    "AK103 GP-30 HE"          => "ak47he.gif"     ,
    "AK103 GP-30 Semi"        => "ak47he.gif"     ,
    "AK103 Red Dot Auto"      => "ak47.gif"       ,
    "AK103 Red Dot Semi"      => "ak47.gif"       ,
    "AK108 GP-30 Auto"        => "ak47he.gif"     ,
    "AK108 GP-30 HE"          => "ak47he.gif"     ,
    "AK108 GP-30 Semi"        => "ak47he.gif"     ,
    "AK108 Red Dot Auto"      => "ak74.gif"       ,
    "AK108 Red Dot Semi"      => "ak74.gif"       ,
    "AK47"                    => "ak47.gif"       ,
    "AK47 - Auto"             => "ak47.gif"       ,
    "AK47 - Semi"             => "ak47.gif"       ,
    "AK47 Auto"               => "ak47.gif"       ,
    "AK47 GP-25 Auto"         => "ak47he.gif"     ,
    "AK47 GP-25 HE"           => "ak47he.gif"     ,
    "AK47 GP-25 Semi"         => "ak47he.gif"     ,
    "AK47 Semi"               => "ak47.gif"       ,
    "AK47/GP-25"              => "ak47he.gif"     ,
    "AK47/GP-25 - Auto"       => "ak47he.gif"     ,
    "AK47/GP-25 - Grenade"    => "ak47he.gif"     ,
    "AK47/GP-25 - Semi"       => "ak47he.gif"     ,
	"AK47/GP-25 Auto"         => "ak47he.gif"     ,
    "AK47/GP-25 Grenade"      => "ak47he.gif"     ,
	"AK47/GP-25 Semi"         => "ak47he.gif"     ,
    "AK74"                    => "ak74.gif"       ,
    "AK74 - Auto"             => "ak74.gif"       ,
    "AK74 - Semi"             => "ak74.gif"       ,
    "AK74 Reflex"             => "ak74.gif"       ,
    "AK74-Reflex-Auto"        => "ak74.gif"       ,
    "AK74-Reflex-Semi"        => "ak74.gif"       ,
    "AK74/GP-25"              => "ak74he.gif"     ,
    "AK74/GP-25 - Auto"       => "ak74he.gif"     ,
    "AK74/GP-25 - Grenade"    => "ak74he.gif"     ,
    "AK74/GP-25 - Semi"       => "ak74he.gif"     ,
    "AK74/GP-25 Grenade"      => "ak74he.gif"     ,
    "AT Missile"              => "vehat.gif"      ,
    "AT4"                     => "at4.gif"        ,
    "ATM"                     => "vehat.gif"      ,
    "Adrenalin Gun"           => "adren.gif"      ,
    "Ancient Ship Cannon"     => "shpcan.gif"     ,
    "Anti Air Artillery"      => "artillery.gif"  ,
    "Anti Tank Mine"          => "atmine.gif"     ,
    "Anti-Tank Mine"          => "atmine.gif"     ,
    "Avenger Turret"          => "avenger.gif"    ,
    "Boat Gun"                => "bcan.gif"       ,
    "Bombs"                   => "bomb.gif"       ,
    "CAR15 - Auto"            => "car15.gif"      ,
    "CAR15 - Semi"            => "car15.gif"      ,
    "CAR15 Auto"              => "car15.gif"      ,
    "CAR15 Rifle - Auto"      => "car15.gif"      ,
    "CAR15 Rifle - Semi"      => "car15.gif"      ,
    "CAR15 Semi"              => "car15.gif"      ,
    "CAR15-Reflex-Auto"       => "car15.gif"      ,
    "CAR15-Reflex-Semi"       => "car15.gif"      ,
    "Car15 Auto"              => "car15.gif"      ,
    "Car15 Reflex"            => "car15.gif"      ,
    "Car15 Semi"              => "car15.gif"      ,
    "Claymore"                => "claymore.gif"   ,
    "Combat Knife"            => "knife.gif"      ,
    "Dual 30mm Cannons"       => "30mm.gif"       ,
    "E M Cannon"              => "emcannon.gif"   ,
    "EE9 Turret"              => "cal.gif"        ,
    "EM Cannon"               => "emcannon.gif"   ,
    "Emplaced M60"            => "m60.gif"        ,
    "FAMAS F1 Auto"           => "famas.gif"      ,
    "FAMAS F1 Semi"           => "famas.gif"      ,
    "FIM-92A Stinger"         => "stinger.gif"    ,
    "FN MAG (GPMG)"           => "fnfnc.gif"      ,
    "FN P90 - Auto"           => "p90.gif"        ,
    "FN P90 - Semi"           => "p90.gif"        ,
    "FN-FNC"                  => "fnfnc.gif"      ,
    "FN-FNC - Auto"           => "fnfnc.gif"      ,
    "FN-FNC - Burst"          => "fnfnc.gif"      ,
    "FN-FNC - Semi"           => "fnfnc.gif"      ,
    "FN-MAG"                  => "fnfnc.gif"      ,
    "FN-P90 Auto"             => "p90.gif"        ,
    "FN-P90 Semi"             => "p90.gif"        ,
    "Flak Cannon"             => "artillery.gif"  ,
    "Flamethrower"            => "flmt.gif"       ,
    "Frag Grenade"            => "frag.gif"       ,
    "G3"                      => "g3.gif"         ,
    "G3 - Auto"               => "g3.gif"         ,
    "G3 - Semi"               => "g3.gif"         ,
    "G3 Rifle - Auto"         => "g3.gif"         ,
    "G3 Rifle - Semi"         => "g3.gif"         ,
    "G36"                     => "g36.gif"        ,
    "G36 - Auto"              => "g36.gif"        ,
    "G36 - Semi"              => "g36.gif"        ,
    "G36 Rifle - Auto"        => "g36.gif"        ,
    "G36 Rifle - Semi"        => "g36.gif"        ,
    "GPMG"                    => "m240.gif"       ,
    "Glock 17"                => "glock17.gif"    ,
    "Glock 17 Silenced"       => "glock17.gif"    ,
    "Glock 18C"               => "glock17.gif"    ,
    "Glock 18C Auto"          => "glock17.gif"    ,
    "Glock 18C Semi"          => "glock17.gif"    ,
    "Grenade Launcher"        => "glauncher.gif"  ,
    "HE Grenade"              => "frag.gif"       ,
    "HELLFIRE"                => "rocket.gif"     ,
    "HK 416 Auto"             => "m16.gif"        ,
    "HK 416 Semi"             => "m16.gif"        ,
    "HK G36E Auto"            => "g36.gif"        ,
    "HK G36E Semi"            => "g36.gif"        ,
    "HK G3A3 Auto"            => "g36.gif"        ,
    "HK G3A3 Semi"            => "g3.gif"         ,
    "HK MP5/10 Auto"          => "mp5.gif"        ,
    "HK MP5/10 Burst"         => "mp5.gif"        ,
    "HK MP5/10 Semi"          => "mp5.gif"        ,
    "HK MP5SD5 Auto"          => "mp5s.gif"       ,
    "HK MP5SD5 Burst"         => "mp5s.gif"       ,
    "HK MP5SD5 Semi"          => "mp5s.gif"       ,
    "HKG36"                   => "g36.gif"        ,
    "HKG36 - Auto"            => "g36.gif"        ,
    "HKG36 - Semi"            => "g36.gif"        ,
    "HYDRA 70mm"              => "rocket.gif"     ,
    "Javelin"                 => "javelin.gif"    ,
    "KA-50 Gun"               => "ka52.gif"       ,
    "KA-52 Gun"               => "ka52.gif"       ,
    "Knife"                   => "knife.gif"      ,
    "Kord Machinegun"         => "kord.gif"       ,
    "L115A"                   => "l115a.gif"      ,
    "L115A Sniper Rifle"      => "l115a.gif"      ,
    "L1A1 Rifle - Auto"       => "l1a1.gif"       ,
    "L1A1 Rifle - Semi"       => "l1a1.gif"       ,
    "L85A1 Auto"              => "l85.gif"        ,
    "L85A1 Semi"              => "l85.gif"        ,
    "L96A1"                   => "l115a.gif"      ,
    "M 60"                    => "m_60.gif"       ,
    "M-870 (00 Buckshot)"     => "shotgun.gif"    ,
    "M-870(SSG Slug)"         => "shotgun.gif"    ,
    "M-9"                     => "m9.gif"         ,
    "M107 .50 Cal"            => "m82.gif"        ,
    "M107 Barret"             => "m82.gif"        ,
    "M16"                     => "m16.gif"        ,
    "M16 - Burst"             => "m16.gif"        ,
    "M16 - Semi"              => "m16.gif"        ,
    "M16 Rifle - Auto"        => "m16.gif"        ,
    "M16 Rifle - Semi"        => "m16.gif"        ,
    "M16/M203"                => "m16he.gif"      ,
    "M16/M203 - Burst"        => "m16he.gif"      ,
    "M16/M203 - Grenade"      => "m16he.gif"      ,
    "M16/M203 - Semi"         => "m16he.gif"      ,
    "M16/M203 Grenade"        => "m16he.gif"      ,
    "M16/M203 Rifle - Auto"   => "m16he.gif"      ,
    "M16/M203 Rifle - Semi"   => "m16he.gif"      ,
    "M16A2 - Burst"           => "m16.gif"        ,
    "M16A2 - Semi"            => "m16.gif"        ,
    "M16A2/M203 - Burst"      => "m16he.gif"      ,
    "M16A2/M203 - Grenade"    => "m16he.gif"      ,
    "M16A2/M203 - Semi"       => "m16he.gif"      ,
    "M16A3"                   => "m16.gif"        ,
    "M16A3 - Auto"            => "m16.gif"        ,
    "M16A3 - Semi"            => "m16.gif"        ,
    "M16A3 Auto"              => "m16.gif"        ,
    "M16A3 Semi"              => "m16.gif"        ,
    "M16A4"                   => "m16.gif"        ,
    "M16A4 M203 Auto"         => "m16he.gif"      ,
    "M16A4 M203 HE"           => "m16he.gif"      ,
    "M16A4 M203 Semi"         => "m16he.gif"      ,
    "M16A4/M203"              => "m16he.gif"      ,
    "M16A4/M203 Grenade"      => "m16he.gif"      ,
    "M18 Claymore"            => "claymore.gif"   ,
    "M1911A"                  => "m19.gif"        ,
    "M1911A1"                 => "m19.gif"        ,
    "M21"                     => "m21.gif"        ,
    "M21 Sniper Rifle"        => "m21.gif"        ,
    "M224 - Frag"             => "mortar.gif"     ,
    "M224 - HE"               => "mortar.gif"     ,
    "M224 Mortar"             => "mortar.gif"     ,
    "M224 Mortar(HE)"         => "mortar.gif"     ,
    "M24"                     => "m24.gif"        ,
    "M24 Sniper Rifle"        => "m24.gif"        ,
    "M240"                    => "m240.gif"       ,
    "M240 Machine Gun"        => "m240.gif"       ,
    "M249"                    => "m249.gif"       ,
    "M249 Machine Gun"        => "m249.gif"       ,
    "M249 SAW"                => "m249.gif"       ,
    "M4"                      => "m4.gif"         ,
    "M4 - Auto"               => "m4.gif"         ,
    "M4 - Semi"               => "m4.gif"         ,
    "M4 Reflex"               => "m4.gif"         ,
    "M4 Rifle - Auto"         => "m4.gif"         ,
    "M4 Rifle - Semi"         => "m4.gif"         ,
    "M4-Reflex-Auto"          => "m4.gif"         ,
    "M4-Reflex-Semi"          => "m4.gif"         ,
    "M4/M203"                 => "m4he.gif"       ,
    "M4/M203 - Auto"          => "m4he.gif"       ,
    "M4/M203 - Grenade"       => "m4he.gif"       ,
    "M4/M203 - Semi"          => "m4he.gif"       ,
    "M4/M203 Grenade"         => "m4he.gif"       ,
    "M4/M203 Rifle - Auto"    => "m4he.gif"       ,
    "M4/M203 Rifle - Semi"    => "m4he.gif"       ,
    "M4A1 Auto"               => "m4.gif"         ,
    "M4A1 M203 Auto"          => "m4he.gif"       ,
    "M4A1 M203 HE"            => "m4he.gif"       ,
    "M4A1 M203 Semi"          => "m4he.gif"       ,
    "M4A1 Semi"               => "m4.gif"         ,
    "M60"                     => "m60.gif"        ,
    "M60 Machine Gun"         => "m60.gif"        ,
    "M82"                     => "m82.gif"        ,
    "M82 .50 Cal"             => "m82.gif"        ,
    "M82 Sniper Rifle"        => "m82.gif"        ,
    "M870 Buckshot"           => "shotgun.gif"    ,
    "M870 SSG Slug"           => "shotgun.gif"    ,
    "M9"                      => "m9.gif"         ,
    "M9 Bayonet"              => "knife.gif"      ,
    "M9 Beretta"              => "m9.gif"         ,
    "M9 Beretta Pistol"       => "m9.gif"         ,
    "MK-23"                   => "mk23.gif"       ,
    "MK-23 Pistol"            => "mk23.gif"       ,
    "MP5 10mm"                => "mp5.gif"        ,
    "MP5 SMG"                 => "mp5s.gif"       ,
    "MP5 SMG Silenced"        => "mp5s.gif"       ,
    "MP5 Silenced"            => "mp5s.gif"       ,
    "MP5/10"                  => "mp5.gif"        ,
    "MP5/10-Aim-Auto"         => "mp5.gif"        ,
    "MP5/10-Aim-Semi"         => "mp5.gif"        ,
    "MP5/SA2"                 => "mp5.gif"        ,
    "MP5/SA2 Aimpoint"        => "mp5.gif"        ,
    "MP5/SD"                  => "mp5s.gif"       ,
    "MP5/SD2"                 => "mp5s.gif"       ,
    "MP5/SD2 Aimpoint"        => "mp5s.gif"       ,
    "MP5SA2"                  => "mp5.gif"        ,
    "MP5SD 9x19 Subsonic"     => "mp5s.gif"       ,
    "MP5SD-Aim-Auto"          => "mp5s.gif"       ,
    "MP5SD-Aim-Semi"          => "mp5s.gif"       ,
    "MP5SD2"                  => "mp5s.gif"       ,
    "Machete"                 => "machete.gif"    ,
    "Masterkey - Semi SG"     => "mkey.gif"       ,
    "Masterkey Rifle - Auto"  => "mkey.gif"       ,
    "Masterkey Rifle - Semi"  => "mkey.gif"       ,
    "Mex 50 Cal Machinegun"   => "cal.gif"        ,
    "Minigun"                 => "minigun.gif"    ,
    "Molotov Cocktail"        => "molot.gif"      ,
    "Mortar"                  => "mortar.gif"     ,
    "P-500 Basalt Launcher"   => "p500.gif"       ,
    "P90"                     => "p90.gif"        ,
    "P90 - Auto"              => "p90.gif"        ,
    "P90 - Semi"              => "p90.gif"        ,
    "P90 SMG - Auto"          => "p90.gif"        ,
    "P90 SMG - Semi"          => "p90.gif"        ,
    "PKM"                     => "pkm.gif"        ,
    "PSG-1"                   => "psg.gif"        ,
    "PSG-1 Rifle"             => "psg.gif"        ,
    "PSG-1 Silenced"          => "psg.gif"        ,
    "PSG-1 Sniper Rifle"      => "psg.gif"        ,
    "PSG-1SD"                 => "psg.gif"        ,
    "RPG-7"                   => "rpg.gif"        ,
    "RPG7"                    => "rpg.gif"        ,
    "RPK-47"                  => "rpk74.gif"      ,
    "RPK-47 SAW"              => "rpk74.gif"      ,
    "RPK-74"                  => "rpk74.gif"      ,
    "RPK-74 Machine Gun"      => "rpk74.gif"      ,
    "Rockets"                 => "rocket.gif"     ,
    "S&W 357 Magnum"          => "magnum.gif"     ,
    "SAM"                     => "vehat.gif"      ,
    "SAM Launcher"            => "p500.gif"       ,
    "SIG 552 - Auto"          => "sig552.gif"     ,
    "SIG 552 - Burst"         => "sig552.gif"     ,
    "SIG 552 - Semi"          => "sig552.gif"     ,
    "SR-25"                   => "sr25.gif"       ,
    "SR-25 Rifle"             => "sr25.gif"       ,
    "SR-25 Silenced"          => "sr25.gif"       ,
    "SVD"                     => "svd.gif"        ,
    "SVD Dragunov"            => "svd.gif"        ,
    "SVD Sniper Rifle"        => "svd.gif"        ,
    "Satchel"                 => "satchel.gif"    ,
    "Satchel Charge"          => "satchel.gif"    ,
    "Shotgun"                 => "shotgun.gif"    ,
    "Shotgun Pump-Action"     => "shgun.gif"      ,
    "Shotgun Semi-Auto"       => "shgun.gif"      ,
    "Shotgun pump"            => "shgun.gif"      ,
    "Sidewinders"             => "rocket.gif"     ,
    "Slug Shotgun"            => "shotgun.gif"    ,
    "Stinger"                 => "stinger.gif"    ,
    "TOW"                     => "stinger.gif"    ,
    "Tactical Nuke"           => "nuke.gif"       ,
    "Thermite Grenade"        => "thermite.gif"   ,
    "Veh 120mm Cannon"        => "veh120.gif"     ,
    "Veh 125mm Cannon"        => "veh125.gif"     ,
    "Veh 155mm Howitzer"      => "155how.gif"     ,
    "Veh 20mm Cannon"         => "veh20.gif"      ,
    "Veh 30mm Cannon"         => "cannon30mm.gif" ,
    "Veh AT Missle"           => "vehat.gif"      ,
    "Veh SAM Launcher"        => "vehat.gif"      ,
    "Walther 2000 Silenced"   => "walt.gif"       ,
    "ZSU-23 50 Cal"           => "cal.gif"        ,
    "ZU-23 Gun"               => "cal.gif"        ,
);